<?php

class gtd_vueeditor extends CModule {

    public $MODULE_ID = 'gtd.vueeditor';

    public $MODULE_NAME = 'Блочный редактор контента';

    public $MODULE_DESCRIPTION = 'Блочный редактор нового поколения';

    public $PARTNER_NAME = 'GTD';

    public $PARTNER_URI = 'http://betaagency.ru';

    public function __construct(){

    }
    public function DoInstall()
    {
        RegisterModule($this->MODULE_ID);
    }

    public function DoUninstall()
    {
        parent::DoUninstall(); // TODO: Change the autogenerated stub
    }

}